// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (C) 2022
 * Kent Hall <kjh2166@columbia.edu>
 */

#ifndef _LINUX_HORIZON_TYPES_H
#define _LINUX_HORIZON_TYPES_H

enum memory_attribute {
	HZN_MEMORY_ATTRIBUTE_LOCKED = (1 << 0),
	HZN_MEMORY_ATTRIBUTE_IPC_LOCKED = (1 << 1),
	HZN_MEMORY_ATTRIBUTE_DEVICE_SHARED = (1 << 2),
	HZN_MEMORY_ATTRIBUTE_UNCACHED = (1 << 3),
};

enum memory_state {
	HZN_MEMORY_STATE_FREE = 0x00,
	HZN_MEMORY_STATE_IO = 0x01,
	HZN_MEMORY_STATE_STATIC = 0x02,
	HZN_MEMORY_STATE_CODE = 0x03,
	HZN_MEMORY_STATE_CODE_DATA = 0x04,
	HZN_MEMORY_STATE_NORMAL = 0x05,
	HZN_MEMORY_STATE_SHARED = 0x06,
	HZN_MEMORY_STATE_ALIAS = 0x07,
	HZN_MEMORY_STATE_ALIAS_CODE = 0x08,
	HZN_MEMORY_STATE_ALIAS_CODE_DATA = 0x09,
	HZN_MEMORY_STATE_IPC = 0x0A,
	HZN_MEMORY_STATE_STACK = 0x0B,
	HZN_MEMORY_STATE_THREAD_LOCAL = 0x0C,
	HZN_MEMORY_STATE_TRANSFERRED = 0x0D,
	HZN_MEMORY_STATE_SHARED_TRANSFERRED = 0x0E,
	HZN_MEMORY_STATE_SHARED_CODE = 0x0F,
	HZN_MEMORY_STATE_INACCESSIBLE = 0x10,
	HZN_MEMORY_STATE_NON_SECURE_IPC = 0x11,
	HZN_MEMORY_STATE_NON_DEVICE_IPC = 0x12,
	HZN_MEMORY_STATE_KERNEL = 0x13,
	HZN_MEMORY_STATE_GENERATED_CODE = 0x14,
	HZN_MEMORY_STATE_CODE_OUT = 0x15,
};

enum memory_permission {
	HZN_MEMORY_PERMISSION_NONE = (0 << 0),
	HZN_MEMORY_PERMISSION_READ = (1 << 0),
	HZN_MEMORY_PERMISSION_WRITE = (1 << 1),
	HZN_MEMORY_PERMISSION_EXECUTE = (1 << 2),
	HZN_MEMORY_PERMISSION_READ_WRITE = HZN_MEMORY_PERMISSION_READ | HZN_MEMORY_PERMISSION_WRITE,
	HZN_MEMORY_PERMISSION_READ_EXECUTE = HZN_MEMORY_PERMISSION_READ | HZN_MEMORY_PERMISSION_EXECUTE,
	HZN_MEMORY_PERMISSION_DONT_CARE = (1 << 28),
};

struct memory_info {
	u64 addr;
	u64 size;
	enum memory_state state;
	enum memory_attribute attr;
	enum memory_permission perm;
	u32 ipc_refcount;
	u32 device_refcount;
	u32 padding;
};

#endif
